### ISSUE TITLE
How can I draw blog's class diagram??

### ISSUE THREAD

**Issue by Jaeyeong-Lee** [drinks-wallet/DrinksRfidTerminal#1]
![image](https://cloud.githubusercontent.com/assets/20218186/18267879/2b124786-745c-11e6-931a-fbc78b138f04.png)

Hi. My name is Lee. 
I'm also arduino big fan.

I saw this class diagram at your blog.

I think it is very clear. 

Do you use some tool?
Then, I want to know the tool.

Thanks. Lee

**Comment by bblanchon** [comment]
Hi Lee,

I used [StarUML](http://staruml.io/).

Regards,
Benoit
